### ISSUE TITLE
The output

### ISSUE THREAD

**Issue by shawshankkumar** [FaizanZaheerGit/StudentPerformancePrediction-ML#1]
Hey, What is the output H, L And M?

**Comment by FaizanZaheerGit** [comment]
It corresponds to the grade/level of education or class, in which the student is studying...

H (High), M (medium), L (lower)

**Comment by FaizanZaheerGit** [comment]
> Hey, What is the output H, L And M?

It corresponds to the grade/level of education or class, in which the student is studying...

H (High), M (medium), L (lower)

**Comment by shawshankkumar** [comment]
Oh, so we enter the grade too right? I do not understand can you please
tell me a little more if possible

**Comment by FaizanZaheerGit** [comment]
Thank you for asking...
it was a bit confusing...

basically H M or L is predicted output of study level (predictor variable) ...
It should not have been part of the input for testing...
I have removed it from input
